#!/usr/bin/sh

ZER0=0000000000000000000000000000000000000000

ANNOTATED_TAG_SHA=`git rev-parse annotated_tag`
UNANNOTED_TAG_SHA=`git rev-parse unannotated_tag`

#example creating new tag
echo "  Create Tag: Authorized user: should pass"
perl update refs/tags/annotated_tag $ZER0 $ANNOTATED_TAG_SHA admin test
echo "  Create Tag: Unauthorized user: should fail"
perl update refs/tags/annotated_tag $ZER0 $ANNOTATED_TAG_SHA reporter test

#example deleting tag
echo "  Delete Tag: Authorized user: should pass"
perl update refs/tags/annotated_tag $ANNOTATED_TAG_SHA $ZER0 admin test
echo "  Delete Tag: Unauthorized user: should fail"
perl update refs/tags/annotated_tag $ANNOTATED_TAG_SHA $ZER0 reporter test

#example updating tag
echo "  Create Tag: Authorized user: should pass"
perl update refs/tags/annotated_tag $UNANNOTED_TAG_SHA $ANNOTATED_TAG_SHA admin test
echo "  Create Tag: Unauthorized user: should fail"
perl update refs/tags/annotated_tag $UNANNOTED_TAG_SHA $ANNOTATED_TAG_SHA reporter test

