#!/usr/bin/perl

my $redmine_url = "http://0.0.0.0:3000";
my $ws_key = "000000";

# Set to true to diagnose issues, false to reduce clutter
my $verbose = 0;
my $test = 1;

if ($verbose) {
  use warnings;
}

my $ref_name = $ARGV[0];
my $old_ref = $ARGV[1];
my $new_ref = $ARGV[2];
my $user = $test ? $ARGV[3] : $ENV{'GIT_COMMITTER_NAME'};
my $project = $ARGV[4] if ($test);


my $zero="0000000000000000000000000000000000000000";


sub trim($)
{
	my $string = shift;
	$string =~ s/^\s+//;
	$string =~ s/\s+$//;
	return $string;
}

sub grant {
  if($verbose) {
    ($reason) = @_;
    print("Access Granted: $reason\n");
  }
  exit(0);
}

sub deny {
  ($reason) = @_;
  print("Access Denied: $reason\n");
  exit(0);
}

sub get_project_identifier {
    my $r = shift;

    my $cfg = Apache2::Module::get_config(__PACKAGE__, $r->server, $r->per_dir_config);
    my $location = $r->location;
    $location =~ s/\.git$// if (defined $cfg->{RedmineGitSmartHttp} and $cfg->{RedmineGitSmartHttp});
    my ($identifier) = $r->uri =~ m{$location/*([^/.]+)};
    $identifier;
}

sub read_url {
	use LWP;
	my $browser = LWP::UserAgent->new;
	
	print "reading @_\n" 	if ($verbose);
  $response = $browser->get( @_ );
  print $response->status_line if ($verbose);
  if( $response->is_success ) {
	  print "Success!!!\n" 	if ($verbose);
    return 1;
  } else {
 	  print "Failure!!!\n" 	if ($verbose);
    return 0;
  }
}

sub allow_create_branch {
	$url = "$redmine_url/$project/git/branch/create?user_name=$user&branch=$_[0]&key=$ws_key";
	print "url = $url\n" 	if ($verbose);
  return read_url($url);
}

sub allow_delete_branch {
	$url = "$redmine_url/$project/git/branch/delete?user_name=$user&branch=$_[0]&key=$ws_key";
	print "url = $url\n" 	if ($verbose);
  return read_url($url);
}

sub allow_update_branch {
	$url = "$redmine_url/$project/git/branch/update?user_name=$user&branch=$_[0]&ff=$_[1]&key=$ws_key";
	print "url = $url\n" 	if ($verbose);
  return read_url($url);
}

sub allow_create_tag {
	$url = "$redmine_url/$project/git/tag/create?user_name=$user&tag=$_[0]&annotated=$_[1]&key=$ws_key";
	print "url = $url\n" 	if ($verbose);
  return read_url($url);
}

sub allow_delete_tag {
  return 0;
}

sub allow_move_tag {
  return 0;
}

my $commit_type;
if ( $new_ref eq $zero) {
  $commit_type = 'delete';
} else {
  $commit_type = trim(`/usr/bin/git cat-file -t $new_ref`);
}

if ($verbose) {
  print("user = $user\n");
  print("ref_name = $ref_name\n");
  print("old_ref = $old_ref\n");
  print("new_ref = $new_ref\n");
  print("commit_type = $commit_type\n\n");
}

if ($ref_name  =~ "^refs/heads/") {
  $short_name = $ref_name;
  $short_name =~ s/refs\/heads\///;

  if ( $verbose ) { print("$short_name is a branch\n"); }

  if ( $old_ref eq $zero ) {
  	if (allow_create_branch($short_name)) {
	  	grant("Permission granted!");  
	  } else {
		  deny("Cannot create branch");
	  }
  } elsif ( $new_ref eq $zero ) {
  	if (allow_delete_branch($short_name)) {
  		grant("Permission granted!");  
  	} else {
	    deny("Cannot delete branch");
    }
  } else {
    #updating an existing branch
    $merge_base = trim(`git merge-base $old_ref $new_ref`);
    if ( $verbose ) { print("merge-base = $merge_base\n") };
    if ( allow_update_branch($short_name, $merge_base ne $old_ref)) {
      grant("Permission granted");
    } else {
      deny("Cannot update branch.");
    }
  }

} elsif ($ref_name  =~ "^refs/tags/") {
  $short_name = $ref_name;
  $short_name =~ s/refs\/tags\///;

  if ( $verbose ) { print("$short_name is a tag\n"); }
  if ( $new_ref eq $zero ) {
  	if ( allow_delete_tag($short_name) ) {
	    grant("Permission granted");
	  } else {
	  	deny("Cannot delete tags");
	 	}
  } elsif ( $old_ref ne $zero ) {
  	if ( allow_update_tag($short_name) ) {
  		grant("Permission granted");  	
    } else {
	    deny("Cannot move tags");
    }
  } elsif ( allow_create_tag($short_name, $commit_type eq "tag") ) {
  	grant("Permission granted");
  } else {
    deny("Cannot create tag");
  } 
} else {
  deny ("$ref_name is not a branch or tag.");
}

deny("Unknown error");







