#!/usr/bin/perl

my $redmine_url = "http://0.0.0.0:3000";
my $ws_key = "my_secret_key";
my $git_root = "/var/www/git/";

# Set to true to diagnose issues, false to reduce clutter
my $verbose = 0;
my $test = 0;

sub trim($)
{
  my $string = shift;
  $string =~ s/^\s+//;
  $string =~ s/\s+$//;
  return $string;
}

sub get_project_identifier {
  my $location = $_[0];
  $location =~ s/\.git$//;
  my ($identifier) = $location =~ m{^$git_root/*([^/.]+)};
  $identifier;
}

sub read_url {
  use LWP;
  my $browser = LWP::UserAgent->new;
  
  print "reading @_\n"  if ($verbose);
  $response = $browser->get( @_ );
  print $response->status_line if ($verbose);
  $message = $response->content;
  if( $response->is_success ) {
    print "Success!!!\n"  if ($verbose);
    return 1;
  } else {
    print "Failure!!!\n"  if ($verbose);
    return 0;
  }
}

my $work_dir = $test ? "/var/www/git/test.git" : trim(`pwd -P`);

my $project_id = get_project_identifier($work_dir);

print("Updating Redmine\n");
read_url("$redmine_url/sys/fetch_changesets?id=$project_id&key=$ws_key" );
